"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.countries = void 0;
exports.countries = {
    page1: {
        "AFG": "Afghanistan",
        "ALB": "Albania",
        "ALG": "Algeria",
        "ASA": "American Samoa",
        "AND": "Andorra",
        "ANG": "Angola",
        "AIA": "Anguilla",
        "ATG": "Antigua and Barbuda",
        "ARG": "Argentina",
        "ARM": "Armenia",
        "ARU": "Aruba",
        "AUS": "Australia",
        "AUT": "Austria",
        "AZE": "Azerbaijan",
        "BAH": "Bahamas (the)",
        "BHR": "Bahrain",
        "BAN": "Bangladesh",
        "BRB": "Barbados",
        "BLR": "Belarus",
        "BEL": "Belgium"
    },
    page2: {
        "BLZ": "Belize",
        "BEN": "Benin",
        "BER": "Bermuda",
        "BHU": "Bhutan",
        "BOL": "Bolivia (Plurinational State of)",
        "BIH": "Bosnia and Herzegovina",
        "BOT": "Botswana",
        "BRA": "Brazil",
        "BRU": "Brunei Darussalam",
        "BUL": "Bulgaria",
        "BFA": "Burkina Faso",
        "BDI": "Burundi",
        "CPV": "Cabo Verde",
        "CAM": "Cambodia",
        "CMR": "Cameroon",
        "CAN": "Canada",
        "CAY": "Cayman Islands (the)",
        "CTA": "Central African Republic (the)",
        "CHA": "Chad",
        "CHI": "Chile"
    },
    page3: {
        "CHN": "China",
        "COL": "Colombia",
        "COM": "Comoros (the)",
        "COD": "Congo (the Democratic Republic of the)",
        "CGO": "Congo (the)",
        "COK": "Cook Islands (the)",
        "CRC": "Costa Rica",
        "CRO": "Croatia",
        "CUB": "Cuba",
        "CUW": "Curaçao",
        "CYP": "Cyprus",
        "CZE": "Czechia",
        "CIV": "Côte d'Ivoire",
        "DEN": "Denmark",
        "DJI": "Djibouti",
        "DMA": "Dominica",
        "DOM": "Dominican Republic (the)",
        "ECU": "Ecuador",
        "EGY": "Egypt",
        "SLV": "El Salvador"
    },
    page4: {
        "EQG": "Equatorial Guinea",
        "ERI": "Eritrea",
        "EST": "Estonia",
        "SWZ": "Eswatini",
        "ETH": "Ethiopia",
        "FRO": "Faroe Islands (the)",
        "FIJ": "Fiji",
        "FIN": "Finland",
        "FRA": "France",
        "GAB": "Gabon",
        "GAM": "Gambia (the)",
        "GEO": "Georgia",
        "GER": "Germany",
        "GHA": "Ghana",
        "GIB": "Gibraltar",
        "GRE": "Greece",
        "GRN": "Grenada",
        "GUM": "Guam",
        "GUA": "Guatemala",
        "GUI": "Guinea"
    },
    page5: {
        "GNB": "Guinea-Bissau",
        "GUY": "Guyana",
        "HAI": "Haiti",
        "HON": "Honduras",
        "HKG": "Hong Kong",
        "HUN": "Hungary",
        "ISL": "Iceland",
        "IND": "India",
        "IDN": "Indonesia",
        "IRN": "Iran (Islamic Republic of)",
        "IRQ": "Iraq",
        "IRL": "Ireland",
        "ISR": "Israel",
        "ITA": "Italy",
        "JAM": "Jamaica",
        "JPN": "Japan",
        "JOR": "Jordan",
        "KAZ": "Kazakhstan",
        "KEN": "Kenya",
        "PRK": "Korea (the Democratic People's Republic of)"
    },
    page6: {
        "KOR": "Korea (the Republic of)",
        "KUW": "Kuwait",
        "KGZ": "Kyrgyzstan",
        "LAO": "Lao People's Democratic Republic (the)",
        "LVA": "Latvia",
        "LBN": "Lebanon",
        "LES": "Lesotho",
        "LBR": "Liberia",
        "LBY": "Libya",
        "LIE": "Liechtenstein",
        "LTU": "Lithuania",
        "LUX": "Luxembourg",
        "MAC": "Macao",
        "MAD": "Madagascar",
        "MWI": "Malawi",
        "MAS": "Malaysia",
        "MDV": "Maldives",
        "MLI": "Mali",
        "MLT": "Malta",
        "MTN": "Mauritania"
    },
    page7: {
        "MRI": "Mauritius",
        "MEX": "Mexico",
        "MDA": "Moldova (the Republic of)",
        "MNG": "Mongolia",
        "MNE": "Montenegro",
        "MSR": "Montserrat",
        "MAR": "Morocco",
        "MOZ": "Mozambique",
        "MYA": "Myanmar",
        "NAM": "Namibia",
        "NEP": "Nepal",
        "NED": "Netherlands (the)",
        "NCL": "New Caledonia",
        "NZL": "New Zealand",
        "NCA": "Nicaragua",
        "NIG": "Niger (the)",
        "NGA": "Nigeria",
        "NOR": "Norway",
        "OMA": "Oman",
        "PAK": "Pakistan"
    },
    page8: {
        "PLE": "Palestine, State of",
        "PAN": "Panama",
        "PNG": "Papua New Guinea",
        "PAR": "Paraguay",
        "PER": "Peru",
        "PHI": "Philippines (the)",
        "POL": "Poland",
        "POR": "Portugal",
        "PUR": "Puerto Rico",
        "QAT": "Qatar",
        "MKD": "Republic of North Macedonia",
        "ROU": "Romania",
        "RUS": "Russian Federation (the)",
        "RWA": "Rwanda",
        "SKN": "Saint Kitts and Nevis",
        "LCA": "Saint Lucia",
        "VIN": "Saint Vincent and the Grenadines",
        "SAM": "Samoa",
        "SMR": "San Marino",
        "STP": "Sao Tome and Principe"
    },
    page9: {
        "KSA": "Saudi Arabia",
        "SEN": "Senegal",
        "SRB": "Serbia",
        "SEY": "Seychelles",
        "SLE": "Sierra Leone",
        "SVK": "Slovakia",
        "SVN": "Slovenia",
        "SOL": "Solomon Islands",
        "SOM": "Somalia",
        "RSA": "South Africa",
        "SSD": "South Sudan",
        "ESP": "Spain",
        "SRI": "Sri Lanka",
        "SDN": "Sudan (the)",
        "SUR": "Suriname",
        "SWE": "Sweden",
        "SUI": "Switzerland",
        "SYR": "Syrian Arab Republic",
        "TJK": "Tajikistan",
        "TAN": "Tanzania, United Republic of"
    },
    page10: {
        "THA": "Thailand",
        "TLS": "Timor-Leste",
        "TOG": "Togo",
        "TGA": "Tonga",
        "TRI": "Trinidad and Tobago",
        "TUN": "Tunisia",
        "TUR": "Turkey",
        "TKM": "Turkmenistan",
        "TCA": "Turks and Caicos Islands (the)",
        "UGA": "Uganda",
        "UKR": "Ukraine",
        "UAE": "United Arab Emirates (the)",
        "ENG": "England",
        "USA": "United States of America (the)",
        "URU": "Uruguay",
        "UZB": "Uzbekistan",
        "VAN": "Vanuatu",
        "VEN": "Venezuela (Bolivarian Republic of)",
        "VIE": "Viet Nam",
        "VGB": "Virgin Islands (British)"
    },
    page11: {
        "VIR": "Virgin Islands (U.S.)",
        "YEM": "Yemen",
        "ZAM": "Zambia",
        "ZIM": "Zimbabwe",
        "WAL": "Wales",
        "SCO": "Scotland",
        "NIR": "Northern Ireland",
        "TPE": "Chinese Taipei",
        "TAH": "Tahiti"
    }
};
//# sourceMappingURL=Countries.js.map