export const videoInfos4 = [
{
    "viewId": 301,
    "actressName": "Tru Kait",
    "actorName": "Scott Nails",
    "channelName": "Brazzers",
    "videoTitle": "Brazzers Exxtra - Who Owns Whom",
    "duration": "32:41",
    "description": "Tru Kait is a special kind of call girl. She demands extremely high payment and yet is practically a fought over commodity - men will do almost anything to spend a single night with the smoking hot brunette. After watching her Brazzers debut, you'll understand what all the fuss is about.",
    "videoUrl": "https://goodporn.to/videos/17348/brazzers-exxtra-who-owns-whom-05-12-2020",
    "channelPageUrl": "",
    "releaseDate": "12 May 2020",
    "viewDate": "11 May 2022"
},
{
    "viewId": 302,
    "actressName": "Belle Elise Rose",
    "actorName": "Steve Holmes",
    "channelName": "Brazzers",
    "videoTitle": "Doctor Adventures - Big Thermometer Energy",
    "duration": "34:34",
    "description": "Bella Elise Rose is a tight teen who loves to fuck. Her blonde hair and bold attitude get her small tits in a lot trouble. And since she just turned 18, she's visiting Dr. Steve Holmes to get a contraceptive! Little does she know; Steve has a different kind of thermometer. His cock has been awarded best cockmometer three years in a row! Seems legit to Bella so she checks just how far she can fit it down her throat! Steve makes sure her vitals are all good by fucking her pussy with his huge cock. Bella takes a big facial and then is set to go! Thanks Dr. Holmes!.",
    "videoUrl": "https://goodporn.to/videos/17296/doctor-adventures-big-thermometer-energy-04-27-2020",
    "channelPageUrl": "",
    "releaseDate": "27 Apr 2020",
    "viewDate": "12 May 2022"
},
{
    "viewId": 303,
    "actressName": "Tina Kay",
    "actorName": "Danny D",
    "channelName": "Brazzers",
    "videoTitle": "Doctor Adventures - Cock Reduction",
    "duration": "34:08",
    "description": "Danny D seeks Tina Kay’s trained medical opinion on whether or not he would be eligible for cock reduction surgery. Cock reduction is an invasive, dangerous procedure and it’s Tina’s job to assure patients they have options- and even in this case, some perks! Tina is a trained medical professional and Danny is in good hands as she sucks, strokes and fucks him into appreciating his natural assets- no alterations necessary!.",
    "videoUrl": "https://goodporn.to/videos/15842/doctor-adventures-cock-reduction-04-04-2018",
    "channelPageUrl": "",
    "releaseDate": "04 Apr 2018",
    "viewDate": "13 May 2022"
},
{
    "viewId": 304,
    "actressName": "Veronica Avluv",
    "actorName": "Damon Dice",
    "channelName": "Naughty America",
    "videoTitle": "My Friend's Hot Mom - Young hung cock saves spooked MILF Veronica Avluv from fears",
    "duration": "37:29",
    "description": "Boo! It ain’t Halloween, but Veronica Avluv’s scared out of her mind. She recently moved into a new house, and it’s making all kinds of noises, and she has her son’s friend Damon witness it to prove she isn’t crazy. He’s over helping her move some things in while her husband and son are camping, and she asks him to stay while she showers because she’s so frightened to be alone and vulnerable. But when he does hear what Veronica’s hearing, after she undresses –naturally – and her big juicy tan-lined tits are out, they both scurry like scaredy cats and hide in the bed! But under the covers is where things turn dark and naughty as the MILF straddles her son’s friend for security…and sex! Who knows if the strange noises will ever end, but the sounds coming out of Veronica as she’s getting fucked will be forever memorable!",
    "videoUrl": "",
    "channelPageUrl": "https://www.naughtyamerica.com/scene/young-hung-cock-saves-spooked-milf-veronica-avluv-from-fears-24259",
    "releaseDate": "21 Jul 2018",
    "viewDate": "13 May 2022"
},
{
    "viewId": 305,
    "actressName": "Lexi Luna",
    "actorName": "Charles Dera",
    "channelName": "Brazzers",
    "videoTitle": "Brazzers Exxtra - Pussy Call",
    "duration": "32:34",
    "description": "After being followed down the street by a car full of catcallers, Lexi decides to give the guys exactly what they wished for – as expected, Lexi’s offer to fuck them on the spot is way more than they can handle. When Charles, a helpful good Samaritan, spo",
    "videoUrl": "https://goodporn.to/videos/15493/brazzers-exxtra-pussy-call-10-14-2017",
    "channelPageUrl": "",
    "releaseDate": "14 Oct 2017",
    "viewDate": "13 May 2022"
},
{
    "viewId": 306,
    "actressName": "Abigail Mac",
    "actorName": "Xander Corvus",
    "channelName": "Realitykings",
    "videoTitle": "Sneaky Sex - Squatter's Rights",
    "duration": "33:16",
    "description": "Abigail Mac knows how to work people – from men, to women, from fucking, to showing off a house to potential buyers. In sky-high heels and a tiny little skirt, she struts around a big mansion as if she owns the place, showing it off as well as she shows off her long, beautiful legs. She’s absolutely killing it, but an unexpected squatter, Xander Corvus, has made a home of the house Abigail is trying to sell. And she is not going to let some hippie ruin her sale! No matter how attractive he is… When Xander Corvus requests a shower before he goes, Abigail agrees, but she has more than a shower in mind. She whips out his huge hard cock and sucks him off under the running water, with the buyers right around the corner! The fuck in the shower before moving on to the bedroom, where he cums all over her pussy and stomach. The only thing that’s left to ask is – will Abigail make the sale? (Spoiler, she does!)",
    "videoUrl": "https://goodporn.to/videos/35350/sneaky-sex-squatter-s-rights-02-08-2020",
    "channelPageUrl": "",
    "releaseDate": "08 Feb 2020",
    "viewDate": "14 May 2022"
},
{
    "viewId": 307,
    "actressName": "Abella Danger",
    "actorName": "Ricky Johnson",
    "channelName": "Brazzers",
    "videoTitle": "Brazzers Exxtra - Lights, CockCam, Action!",
    "duration": "34:00",
    "description": "Abella Danger is so captivated by her new CockCam – which she’s using to film a solo tease for her fans – that she misses her call time on set. When she finally shows up, she mistakes custodian Ricky Johnson for the director, and despite the absence of conventional equipment, they use the CockCam to start filming a uniquely intimate, and sexy, scene of their own.",
    "videoUrl": "https://goodporn.to/videos/16860/brazzers-exxtra-lights-cockcam-action-09-18-2019",
    "channelPageUrl": "",
    "releaseDate": "18 Sep 2019",
    "viewDate": "14 May 2022"
},
{
    "viewId": 308,
    "actressName": "Aidra Fox",
    "actorName": "Keiran Lee",
    "channelName": "Brazzers",
    "videoTitle": "Brazzers Exxtra - My Sister-In-Law For Breakfast",
    "duration": "36:13",
    "description": "The sexy Aidra Fox comes into the kitchen, ready to make breakfast. She's got her headphones on and dances around the room. Her sweet dance music keeps her from hearing brother-in-law Keiran Lee sneak up behind her. Turns out that Aidra's husband let Keiran stay over... which is bad news for Aidra's husband. These two used to date and they still have sexual tension to spare. Keiran's cock interrupts Aidra's breakfast plans and these two former lovers spend the morning fucking instead.",
    "videoUrl": "https://goodporn.to/videos/39666/brazzers-exxtra-my-sister-in-law-for-breakfast-03-14-2021",
    "channelPageUrl": "",
    "releaseDate": "14 Mar 2021",
    "viewDate": "15 May 2022"
},
{
    "viewId": 309,
    "actressName": "Cory Chase & Aubrey Rose",
    "actorName": "Johnny Castle",
    "channelName": "Brazzers",
    "videoTitle": "Milfs Like it Big - Tight And Tanned: Part 2",
    "duration": "37:43",
    "description": "After being disciplined by her boss in the best way possible, Aubrey rushes off to help a new customer in the tanning salon. Little does she know that this new customer was spying on her scissoring her boss just moments before. Seeing a hot milf fucking a tight teen made him forget all about tanning, and he offers Aubrey cash to get naked. Aubrey hates working and loves to fuck so it doesn't take much to convince her to take off her clothes and masturbate for this horny stranger. It's not long before Aubrey's boss Cory walks in on them, but instead of getting mad at her slutty employee she decides to get a piece of that big cock for herself.",
    "videoUrl": "https://goodporn.to/videos/14895/milfs-like-it-big-tight-and-tanned-part-2-12-11-2016",
    "channelPageUrl": "",
    "releaseDate": "11 Dec 2016",
    "viewDate": "16 May 2022"
},
{
    "viewId": 310,
    "actressName": "Juelz Ventura",
    "actorName": "Keiran Lee",
    "channelName": "Brazzers",
    "videoTitle": "Real Wife Stories - Any Friend Of Yours Is A Friend Of Mine",
    "duration": "34:15",
    "description": "Juelz has been living on the lesbian side of bisexual for some time now. But when Juelz' wife introduces her to her new boss, Keiran, they pretend they're just friends as they don't know how conservative he may be. However, this means Keiran thinks Juelz is fully available...and his flirting brings up her old longing for some thick dick.",
    "videoUrl": "https://goodporn.to/videos/15447/real-wife-stories-any-friend-of-yours-is-a-friend-of-mine-09-18-2017",
    "channelPageUrl": "",
    "releaseDate": "18 Sep 2017",
    "viewDate": "16 May 2022"
},
{
    "viewId": 311,
    "actressName": "Kimmy Granger",
    "actorName": "Xander Corvus",
    "channelName": "Brazzers",
    "videoTitle": "ZZ Series - Power Bangers: A XXX Parody Part 1",
    "duration": "26:59",
    "description": "Five typical college students have no idea evil is headed towards Earth, or that they will be the ones chosen to fight it. For now they're at a house party where the nerdy girl is hoping the hot jock will notice her. She lucks out when he takes her upstai",
    "videoUrl": "https://goodporn.to/videos/15155/zz-series-power-bangers-a-xxx-parody-part-1-04-21-2017",
    "channelPageUrl": "",
    "releaseDate": "21 Apr 2017",
    "viewDate": "16 May 2022"
},
{
    "viewId": 400,
    "actressName": "",
    "actorName": "",
    "channelName": "",
    "videoTitle": "",
    "duration": "00:00",
    "description": "",
    "videoUrl": "",
    "channelPageUrl": "",
    "releaseDate": "",
    "viewDate": ""
}
]